name: Docker Image CI

on:
  push:
    tags:
      - '1.*.*-release-*'
  workflow_dispatch:
      
permissions:
  contents: read
  id-token: write 
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<ACTIONS_ROLE>
        aws-region: us-east-2

    - name: Amazon ECR "Login" Action for GitHub Actions
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Build, tag, and push Docker image to ECR
      env:
        ECR_REGISTRY: <ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com
        ECR_REPOSITORY: <REPO_NAME>
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
          
