name: Update K8s Manifests

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-manifests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

    steps:
    - name: Checkout manifests repo
      uses: actions/checkout@v4
      with:
        repository: Seek-challenges/k8s-manifests
        token: ${{ secrets.GH_PAT }}
        path: k8s-manifests

    - name: Update image tag in values.yaml
      run: |
        cd k8s-manifests/$SERVICE_NAME
        echo "Actualizando tag de imagen a: ${{ github.event.workflow_run.head_branch }} para el servicio $SERVICE_NAME"
        sed -i "s/^\([[:space:]]*tag:[[:space:]]*\).*/\1${{ github.event.workflow_run.head_branch }}/" values.yaml

    - name: Commit and push changes
      run: |
        cd k8s-manifests
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add $SERVICE_NAME/values.yaml
        git commit -m "Update $SERVICE_NAME image tag to ${{ github.event.workflow_run.head_branch }}"
        git push
